models/Notificaridiriginte.php
<?php

namespace app\models;

use Yii;
use yii\bootstrap\Html;
use app\models\autoGenerated\NotificaridiriginteGenerated;
use yii\data\ActiveDataProvider;

class Notificaridiriginte extends NotificaridiriginteGenerated
{
    /**
     * @param $id_notificare
     * @return array|null|\yii\db\ActiveRecord
     * returneaza inregistrarea cu id-ul dat din tabla notificaridiriginte
     */
    public static function getNotificare($id_notificare)
    {
        $notificare = Notificaridiriginte::find()->where([
            'id' => $id_notificare
        ])->one();
        return $notificare;
    }

    /**
     * @return int
     * returneaza numarul notificarilor nerezolvate
     */
    public static function getNrNotificariNerezolvate($id_clasa)
    {
        $notificari = Notificaridiriginte::findAll([
            'statut' => 'nerezolvat',
            'id_clasa' => $id_clasa
        ]);
        return count($notificari);
    }

    /**
     * @param $dataProvider
     * @return array
     * returneaza un array cu elevii selectati  din clasa dirigintelui
     **/
    public static function getEleviSelectati($dataProvider)
    {
        $lista_elevi = array();
        for ($i = 0; $i < count($dataProvider->getModels()); $i++) {
            $nume_elev = $dataProvider->getModels()[$i]['nume'] . ' ' . $dataProvider->getModels()[$i]['prenume'];
            $lista_elevi[$i] = $nume_elev;
            //$lista_elevi[$dataProvider->getModels()[$i]['email']]=$nume_elev;
        }
        return $lista_elevi;

    }

    /**
     * @param $lista_iduri
     * @param $lista_elevi
     * @return array
     * returneaza un array cu e-mailurile elevilor selectati din clasa dirigintelui
     */
    public static function getEmailEleviSelectati($lista_iduri, $lista_elevi)
    {
        $lista_emailuri = array();
        for ($i = 0; $i < count($lista_iduri); $i++) {
            $email = $lista_elevi[$lista_iduri[$i]]['email'];
            $nume_elev = $lista_elevi[$lista_iduri[$i]]['nume'] . ' ' . $lista_elevi[$lista_iduri[$i]]['prenume'];
            $lista_emailuri[$email] = $nume_elev;
        }
        return $lista_emailuri;

    }

    public static function getNotificariElev($nr_matricol, $an_scolar)
    {

        $query = Notificaridiriginte::find();
        $query->andFilterWhere([
            'nr_matricol' => $nr_matricol,
            'an_scolar' => $an_scolar
        ]);
//        $notificari=Notificaridiriginte::find()
//            ->where(['nr_matricol'=>$nr_matricol])
//            ->all();

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 10
            ]
        ]);

        return $dataProvider;
    }

    /**
     * Trimite un e-mail elevilor selectati de dirigintele clasei.
     *
     * @param string $email_profesor
     *            - Emailul profesorului.
     * @param string $linksite
     *            - Link-ul site-ului.
     * @param string $parola
     *            - Parola.
     */
    public function sendMailEleviSelectati($lista_emailuri, $notificarea)
    {
        $sablon_mail = new Constante();
        $mailcontent = $sablon_mail->getSablonMailPentruNotificareElevi($notificarea);
        // trimit e-mail
        Yii::$app->mailer->compose()
            ->setFrom($sablon_mail->getEmailHost())
            ->setTo($lista_emailuri)
            ->setSubject($sablon_mail->getNumeProiect() . ' - notificare')
            ->setTextBody('Plain text content')
            ->setHtmlBody($mailcontent)
            ->send();
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if ($insert) {
                //dace este create

            } else {
                //daca este update

            }
            // indiferent daca este inserare sau actualizare se introduce data curenta in campul data_actualizarii
            $this->data_actualizarii = date('Y-m-d H:i:s');
            return true;
        } else {

            return false;
        }
    }
}

controllers/NotificaridiriginteController.php
<?php
namespace app\controllers;

use app\controllers\autoGenerated\NotificaridiriginteControllerGenerated;
use app\models\Diriginti;
use app\models\Elevi;
use app\models\Listaclase;
use app\models\Notificaridiriginte;
use app\models\NotificaridiriginteSearch;
use Yii;

/**
 *
 * @author dan.nicoara
 *
 */
class NotificaridiriginteController extends NotificaridiriginteControllerGenerated
{

    /**
     * Lists all Notificaridiriginte models.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        if (isset(Yii::$app->session['id_clasa']))
            $id_clasa = Yii::$app->session['id_clasa'];
        else
            return $this->redirect([
                'site/index'
            ]);

        $searchModel = new NotificaridiriginteSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $dataProvider->query->andWhere([
            'id_clasa' => $id_clasa,
        ]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider
        ]);
    }
    /**
     * Updates an existing Notificaridiriginte model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $este_elevul_conectat = isset(Yii::$app->session['user']->role) ?
                                    Yii::$app->session['user']->role == 'elev' :
                                    false;
        if (!$este_elevul_conectat)
            return $this->redirect([
                'site/index'
            ]);
        
        $model = $this->findModel($id);

        $nr_matricol = Yii::$app->session['user']->nr_matricol;
        $nume_elev = Yii::$app->session['user']->nume;
        $prenume_elev = Yii::$app->session['user']->prenume;
        $an_scolar = \Yii::$app->params['anul_scolar'];
        $id_clasa = Elevi::getIdClasa($nr_matricol, $an_scolar);
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            {
                Yii::$app->session->setFlash('success', "Notificarea a fost editata si trimisa dirigintelui !");
                return $this->redirect([
                    'site/index'
                ]);
            }

        } else {
            return $this->render('update', [
                'model' => $model,
                'nr_matricol' => $nr_matricol,
                'nume_elev' => $nume_elev,
                'prenume_elev' => $prenume_elev,
                'id_clasa' => $id_clasa,
                'an_scolar' => $an_scolar
            ]);
        }
    }

    /**
     * Creates a new Notificaridiriginte model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @return mixed
     */
    public function actionCreate()
    {
        $este_elevul_conectat = isset(Yii::$app->session['user']->role) ?
                                    Yii::$app->session['user']->role == 'elev' :
                                    false;

        if (!$este_elevul_conectat || !Elevi::emailCorect()) {
            Yii::$app->session->setFlash('error', 'Pentru a continua , trebuie sa va conectati cu o adresa de e-mail valida !!!');
            return $this->redirect([
                'site/index'
            ]);
        }

        $model = new Notificaridiriginte();

        $nr_matricol = Yii::$app->session['user']->nr_matricol;
        $nume_elev = Yii::$app->session['user']->id;
        $prenume_elev = Yii::$app->session['user']->prenume;
        $an_scolar = \Yii::$app->params['anul_scolar'];
        $id_clasa = Elevi::getIdClasa($nr_matricol, $an_scolar);
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect([
                'view',
                'id' => $model->id
            ]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'nr_matricol' => $nr_matricol,
                'nume_elev' => $nume_elev,
                'prenume_elev' => $prenume_elev,
                'id_clasa' => $id_clasa,
                'an_scolar' => $an_scolar
            ]);
        }
    }

    /**
     * Deletes an existing Notificaridiriginte model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     *
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        Yii::$app->session->setFlash('success', "Notificarea  a fost stearsa din lista !");
        return $this->redirect([
            'index'
        ]);
    }

    /**
     *
     * @param
     *            $id_notificare
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException Dirigintele actualizeaza statutul unei notificari din tabla notificaridiriginte
     */
    public function actionActualizeaza($id_notificare)
    {
        $notificare = Notificaridiriginte::getNotificare($id_notificare);
        
        $model = $this->findModel($id_notificare);
        
        $nr_matricol = $notificare['nr_matricol'];
        $id_clasa = $notificare['id_clasa'];
        $nume_elev = $notificare['nume'];
        $prenume_elev = $notificare['prenume'];
        $an_scolar = \Yii::$app->params['anul_scolar'];
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            {
                Yii::$app->session['numar_notificari_nerezolvate'] = Notificaridiriginte::getNrNotificariNerezolvate($id_clasa);
                return $this->redirect([
                    'notificaridiriginte/index'
                ]);
            }
        } else {
            return $this->render('update', [
                'model' => $model,
                'nr_matricol' => $nr_matricol,
                'nume_elev' => $nume_elev,
                'prenume_elev' => $prenume_elev,
                'id_clasa' => $id_clasa,
                'an_scolar' => $an_scolar
            ]);
        }
    }

    /**
     *
     * @param
     *            $id_notificare
     * @return \yii\web\Response
     * @throws NotFoundHttpException
     * @throws \Exception
     * @throws \Throwable Dirigintele sterge o notificare din tabla notificaridiriginte
     */
    public function actionSterge($id_notificare)
    {
        $this->findModel($id_notificare)->delete();
        return $this->redirect([
            'notificaridiriginte/index'
        ]);
    }

    /**
     *
     * @return string|\yii\web\Response dirigintele selecteaza elevii din clasa, carora doreste sa le trimita un e-mail si trimite e-mailul
     */
    public function actionTrimitEmailElevi()
    {
        $este_dirigintele_conectat = isset(Yii::$app->session['user']->role) ?
                                        Yii::$app->session['user']->role == 'diriginte' :
                                        false;

        if ($este_dirigintele_conectat) {
            $model = new Notificaridiriginte();
            
            // obtin id-ul dirigintelui pentru a obtine id-ul clasei dirigintelui
            $id_diriginte = Yii::$app->session['user']->id;
            $id_clasa = Diriginti::getIdClasa($id_diriginte);
            $nume_clasa = Listaclase::getNumeClasa($id_clasa);
            $an_scolar = \Yii::$app->params['anul_scolar'];
            $dataProvider = Diriginti::selectezEleviiClasei($id_clasa, $an_scolar);
            
            if (isset($_GET['Notificaridiriginte'])) {
                // obtin id-urile elevilor selectati si apoi e-mailurile acestore
                $lista_iduri = $_GET['Notificaridiriginte']['id'];
                $lista_emailuri = Notificaridiriginte::getEmailEleviSelectati($lista_iduri, $dataProvider->getModels());
                $mailcontent = $_GET['Notificaridiriginte']['notificarea'];
                
                $model->sendMailEleviSelectati($lista_emailuri, $mailcontent);
                Yii::$app->session->setFlash('success', 'E-mailul a fost expediat !!!');

                return $this->redirect([
                    'site/index',
                ]);
            }
            
            $lista_elevilor_clasei = Notificaridiriginte::getEleviSelectati($dataProvider);
            
            return $this->render('setemailmesaj', [
                'model' => $model,
                'id_clasa' => $id_clasa,
                'nume_clasa' => $nume_clasa,
                'lista_elevi' => $lista_elevilor_clasei
            ]);
        } else
            return $this->redirect([
                'site/index'
            
            ]);
    }

    /**
     * Displays a single Notificaridiriginte model.
     *
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $este_elevul_conectat = isset(Yii::$app->session['user']->role) ?
                                    Yii::$app->session['user']->role == 'elev' :
                                    false;
        if (!$este_elevul_conectat)
            return $this->redirect([
                'site/index'
            ]);
        $nr_matricol = Yii::$app->session['user']->nr_matricol;
        $an_scolar = $anul_scolar = \Yii::$app->params['anul_scolar'];
        $id_clasa = Elevi::getIdClasa($nr_matricol, $an_scolar);
        
        return $this->render('view', [
            'model' => $this->findModel($id),
            'id_clasa' => $id_clasa
        ]);
    }

    /**
     * @return \yii\web\Response
     * se afiseaza notificarile facute de elev pentru diriginte
     */
    public function actionAfisezNotificarileElevului()
    {
        $este_elevul_conectat = isset(Yii::$app->session['user']->role) ?
                                    Yii::$app->session['user']->role == 'elev' :
                                    false;

        if (!$este_elevul_conectat || !Elevi::emailCorect()) {

views/notificaridiriginte/_form.php
<?php

use kartik\select2\Select2;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Notificaridiriginte */
/* @var $form yii\widgets\ActiveForm */

$este_dirigintele_conectat = isset(Yii::$app->session['user']->role) ?
                                        Yii::$app->session['user']->role == 'diriginte' :
                                        false;
?>

<div class="notificaridiriginte-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nr_matricol')->textInput(['maxlength' => true, 'value' => $nr_matricol, 'readonly' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'id_clasa')->textInput(['value' => $id_clasa, 'readonly' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'nume')->textInput(['maxlength' => true, 'value' => $nume_elev, 'readonly' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'prenume')->textInput(['maxlength' => true, 'value' => $prenume_elev, 'readonly' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'an_scolar')->textInput(['maxlength' => true, 'value' => $an_scolar, 'readonly' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'notificarea')->textarea(['maxlength' => 500, 'rows' => 11, 'cols' => 50, 'style' => 'width:400px', 'readonly' => $este_dirigintele_conectat])->hint('Max 500 caractere.') ?>

    <?= $form->field($model, 'statut')->widget(Select2::classname(), [
        'data' => ['nerezolvat' => 'nerezolvat', 'rezolvat' => 'rezolvat'],
        'language' => 'ro',
        'options' => ['placeholder' => 'Seteaza statutul notificarii ...', 'value' => 'nerezolvat'],
        'pluginOptions' => [
            'allowClear' => true,
            'disabled' => !$este_dirigintele_conectat,
            'width' => '400px'
        ],
    ])->label('Seteaza statutul notificarii'); ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Adauga notificarea' : 'Editeaza notificarea', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>

        <?= Html::a('Renunta', ['site/index'], ['class' => 'btn btn-danger']) ?>

    </div>

    <?php ActiveForm::end(); ?>

</div>

views/notificaridiriginte/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\NotificaridiriginteSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="notificaridiriginte-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'nr_matricol') ?>

    <?= $form->field($model, 'id_clasa') ?>

    <?= $form->field($model, 'nume') ?>

    <?= $form->field($model, 'prenume') ?>

    <?php // echo $form->field($model, 'notificarea') ?>

    <?php // echo $form->field($model, 'an_scolar') ?>

    <?php // echo $form->field($model, 'statut') ?>

    <?php // echo $form->field($model, 'data_inregistrarii') ?>

    <?php // echo $form->field($model, 'data_actualizarii') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/notificaridiriginte/afisarenotificarielev.php
<?php

use app\models\Elevi;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\NotificaridiriginteSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
$nume_elev = Elevi::getNumeElev($nr_matricol) . ' ' . Elevi::getPrenumeElev($nr_matricol);
$this->title = 'Notificarile facute dirigintelui de catre : ' . $nume_elev;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="notificaridiriginte-index">

    <h4><?= Html::encode($this->title) ?></h4>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    <br>

    <p>
        <?= Html::a('Revenire pagina principala', ['site/index'], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Adauga notificare  pentru diriginte', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <br>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            'nr_matricol',
            //'id_clasa',
            'nume',
            'prenume',
            'notificarea',
            [
                'label' => 'Anul scolar',
                'content' => function ($data) {
                    $an_scolar = $data['an_scolar'];
                    return $an_scolar;
                },
                'format' => 'text'
            ],
            //'an_scolar',
            'statut',
            [
                'label' => 'Data inregistrarii notificarii',
                'content' => function ($data) {
                    $data_inregistrarii = $data['data_inregistrarii'];
                    return $data_inregistrarii;
                },
                'format' => 'text'
            ],
            [
                'label' => 'Data actualizarii notificarii',
                'content' => function ($data) {
                    $data_actualizarii = $data['data_inregistrarii'];
                    return $data_actualizarii;
                },
                'format' => 'text'
            ],
            //'data_inregistrarii',
            //'data_actualizarii',
        ],
    ]); ?>

</div>

views/notificaridiriginte/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Notificaridiriginte */

$this->title = 'Adauga notificare pentru diriginte';
$this->params['breadcrumbs'][] = ['label' => 'Notificari diriginte', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="notificaridiriginte-create">

    <h4><?= Html::encode($this->title) ?></h4>

    <?= $this->render('_form', [
        'model' => $model,
        'nr_matricol' => $nr_matricol,
        'nume_elev' => $nume_elev,
        'prenume_elev' => $prenume_elev,
        'id_clasa' => $id_clasa,
        'an_scolar' => $an_scolar
    ]) ?>

</div>

views/notificaridiriginte/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\NotificaridiriginteSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Notificarile dirigintelui';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="notificaridiriginte-index">

    <h4><?= Html::encode($this->title) ?></h4>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?php //= Html::a('Adauga notificare  pentru diriginte', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            'nr_matricol',
            //'id_clasa',
            'nume',
            'prenume',
            'notificarea',
            'an_scolar',
            'statut',
            'data_inregistrarii',
            'data_actualizarii',

            ['class' => 'yii\grid\ActionColumn',
                'template' => '{update} {delete} ',
                'buttons' => [
                    'update' => function ($url, $model, $id) {
                        $url = Yii::$app->urlManager->createUrl(['notificaridiriginte/actualizeaza', 'id_notificare' => $id]);
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, ['title' => Yii::t('app', 'Editeaza notificarea')]);
                    },
                    'delete' => function ($url, $model, $id) {
                        $url = Yii::$app->urlManager->createUrl(['notificaridiriginte/sterge', 'id_notificare' => $id]);
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, ['title' => Yii::t('app', 'Sterge notificarea')]);
                    },
                ]

            ],
        ],
    ]); ?>
    <?= Html::a('Revenire pagina principala', ['site/index'], ['class' => 'btn btn-primary']) ?>

</div>

views/notificaridiriginte/setemailmesaj.php
<?php
use kartik\select2\Select2;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>
<?php
$this->title = 'Selectare elevi din clasa  : ' . $nume_clasa;
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="site-about">
    <h4><?= Html::encode($this->title) ?></h4>

    <div class="emailElevi-form">

        <?php $form = ActiveForm::begin([
            'action' => ['notificaridiriginte/trimit-email-elevi'],
            'method' => 'get',
        ]);
        ?>
        <?php
        echo $form->field($model, 'id')->widget(Select2::classname(), [
            'name' => 'elevii',
            'data' => $lista_elevi,
            'language' => 'ro',
            'size' => 'md',
            'options' => ['placeholder' => 'Selecteaza elevii ...'],
            'pluginOptions' => [
                'allowClear' => true,
                'multiple' => true,
                'width' => '300px'
            ],
        ])->label('Selecteaza elevii');
        ?>

        <?= $form->field($model, 'notificarea')->textarea(['maxlength' => 500, 'rows' => 11, 'cols' => 50, 'style' => 'width:400px'])->hint('Max 500 caractere.')->label('Subiectul e-mailului') ?>

        <div class="form-group">
            <?= Html::submitButton('Trimite', ['class' => 'btn btn-success']) ?>
            <?= Html::a('Renunta', ['site/index'], ['class' => 'btn btn-danger']) ?>

        </div>

        <?php ActiveForm::end(); ?>


    </div>

</div>

views/notificaridiriginte/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Notificaridiriginte */
$diriginte = \app\models\Diriginti::getDiriginteDupaIdClasa($id_clasa);
$nume = $diriginte['nume'];
$prenume = $diriginte['prenume'];

$this->title = 'Editeaza notificarea catre dirigintele: ' . $nume . ' ' . $prenume;
$this->params['breadcrumbs'][] = ['label' => 'Notificari diriginte', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Editeaza';
?>
<div class="notificaridiriginte-update">

    <h4><?= Html::encode($this->title) ?></h4>

    <?= $this->render('_form', [
        'model' => $model,
        'nr_matricol' => $nr_matricol,
        'nume_elev' => $nume_elev,
        'prenume_elev' => $prenume_elev,
        'id_clasa' => $id_clasa,
        'an_scolar' => $an_scolar
    ]) ?>

</div>

views/notificaridiriginte/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Notificaridiriginte */
$diriginte = \app\models\Diriginti::getDiriginteDupaIdClasa($id_clasa);
$nume = $diriginte['nume'];
$prenume = $diriginte['prenume'];

$this->title = $nume . ' ' . $prenume;
$this->params['breadcrumbs'][] = ['label' => 'Notificari diriginte', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="notificaridiriginte-view">

    <h4><?= Html::encode('Notificare pentru diriginte') ?></h4>

    <p>
        <?= Html::a('Editeaza notificarea', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Sterge notificarea', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
        <?= Html::a('Revenire pagina principala', ['site/index'], ['class' => 'btn btn-primary']) ?>

    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'nr_matricol',
            'id_clasa',
            'nume',
            'prenume',
            'notificarea',
            'an_scolar',
            'statut',
            'data_inregistrarii',
            'data_actualizarii',
        ],
    ]) ?>

</div>