models/Infodiriginti.php
<?php
namespace app\models;

use app\models\autoGenerated\InfodirigintiGenerated;
use Yii;
use yii\data\ActiveDataProvider;

class Infodiriginti extends InfodirigintiGenerated
{
    /**
     * Selectare informatii despre profesor.
     *
     * @param string $mail_profesor
     *            - Emailul profesorului.
     *            
     * @return ActiveDataProvider
     */
    public static function selectInfodiriginte($mail_diriginte)
    {
        $query = Infodiriginti::find()->joinWith('diriginti');
        
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 2
            ]
        ]);
        
        $query->andFilterWhere([
            'email' => $mail_diriginte
            // 'parola'=> $this->parola,
        ]);
        return $dataProvider;
    }

    public function getDiriginti()
    {
        return $this->hasOne(Diriginti::className(), [
            'id' => 'fk_diriginte'
        ]);
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            // indiferent daca este inserare sau actualizare se introduce data curenta in campul data_actualizarii
            $this->data_actualizarii = date('Y-m-d H:i:s');
            return true;
        } else {
            return false;
        }
    }
}

controllers/InfodirigintiController.php
<?php
namespace app\controllers;

use app\controllers\autoGenerated\InfodirigintiControllerGenerated;
use app\models\Diriginti;
use app\models\Infodiriginti;
use Yii;

/**
 * InfodirigintiController implements the CRUD actions for Infodiriginti model.
 */
class InfodirigintiController extends InfodirigintiControllerGenerated
{

    /**
     * Lists all Infodiriginti models.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $este_dirigintele_conectat = isset(Yii::$app->session['user']->role) ?
                                        Yii::$app->session['user']->role == 'diriginte' :
                                        false;

        $este_administratorul_conectat = isset(Yii::$app->session['user']->role) ?
            Yii::$app->session['user']->role == 'admin' :
            false;

        $este_directorul_conectat = isset(Yii::$app->session['user']->role) ?
            Yii::$app->session['user']->role == 'director' :
            false;
        $este_secretarul_conectat = isset(Yii::$app->session['user']->role) ?
            Yii::$app->session['user']->role == 'secretar' :
            false;

        if (!$este_administratorul_conectat &&
            !$este_directorul_conectat &&
            !$este_secretarul_conectat &&
            !$este_dirigintele_conectat
        ) {
            Yii::$app->session->setFlash('error', 'Nu aveti drepturi pentru a accesa aceasta sectiune !!!');
            return $this->redirect([
                'site/index'
            ]);
        }
        $searchModel = new InfodirigintiSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * Displays a single Infodiriginti model.
     *
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $este_dirigintele_conectat = isset(Yii::$app->session['user']->role) ?
                                        Yii::$app->session['user']->role == 'diriginte' :
                                        false;

        $este_administratorul_conectat = isset(Yii::$app->session['user']->role) ?
            Yii::$app->session['user']->role == 'admin' :
            false;
        $este_directorul_conectat = isset(Yii::$app->session['user']->role) ?
            Yii::$app->session['user']->role == 'director' :
            false;
        $este_secretarul_conectat = isset(Yii::$app->session['user']->role) ?
            Yii::$app->session['user']->role == 'secretar' :
            false;

        if (!$este_administratorul_conectat &&
            !$este_directorul_conectat &&
            !$este_secretarul_conectat &&
            !$este_dirigintele_conectat
        ) {
            Yii::$app->session->setFlash('error', 'Nu aveti drepturi pentru a accesa aceasta sectiune !!!');
            return $this->redirect([
                'site/index'
            ]);
        }
        return $this->render('view', [
            'model' => $this->findModel($id)
        ]);
    }

    /**
     * Creates a new Infodiriginti model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @return mixed
     */
    public function actionCreate()
    {
        $este_administratorul_conectat = isset(Yii::$app->session['user']->role) ?
                                    Yii::$app->session['user']->role == 'admin' :
                                    false;

        $este_directorul_conectat = isset(Yii::$app->session['user']->role) ?
            Yii::$app->session['user']->role == 'director' :
            false;

        if (!$este_administratorul_conectat &&
            !$este_directorul_conectat
        ) {
            Yii::$app->session->setFlash('error', 'Nu aveti drepturi pentru a accesa aceasta sectiune !!!');
            return $this->redirect([
                'site/index'
            ]);
        }
        $model = new Infodiriginti();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect([
                'view',
                'id' => $model->id
            ]);
        }

        return $this->render('create', [
            'model' => $model
        ]);
    }

    /**
     * Updates an existing Infodiriginti model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $este_administratorul_conectat = isset(Yii::$app->session['user']->role) ?
            Yii::$app->session['user']->role == 'admin' :
            false;

        $este_directorul_conectat = isset(Yii::$app->session['user']->role) ?
            Yii::$app->session['user']->role == 'director' :
            false;

        if (!$este_administratorul_conectat &&
            !$este_directorul_conectat
        ) {
            Yii::$app->session->setFlash('error', 'Nu aveti drepturi pentru a accesa aceasta sectiune !!!');
            return $this->redirect([
                'site/index'
            ]);
        }
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect([
                'view',
                'id' => $model->id
            ]);
        }

        return $this->render('update', [
            'model' => $model
        ]);
    }

    /**
     * Deletes an existing Infodiriginti model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     *
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $este_administratorul_conectat = isset(Yii::$app->session['user']->role) ?
            Yii::$app->session['user']->role == 'admin' :
            false;

        $este_directorul_conectat = isset(Yii::$app->session['user']->role) ?
            Yii::$app->session['user']->role == 'director' :
            false;
        if (!$este_administratorul_conectat &&
            !$este_directorul_conectat
        ) {
            Yii::$app->session->setFlash('error', 'Nu aveti drepturi pentru a accesa aceasta sectiune !!!');
            return $this->redirect([
                'site/index'
            ]);
        }
        $this->findModel($id)->delete();

        return $this->redirect([
            'index'
        ]);
    }
    /**
     * Afiseaza datele dirigintelui.
     * A se vedea comentariul de la metoda anterioara.
     */
    public function actionContDiriginte()
    {
        $este_dirigintele_conectat = isset(Yii::$app->session['user']->role) ?
                                        Yii::$app->session['user']->role == 'diriginte' :
                                        false;

        if ($este_dirigintele_conectat) {
            // dirigintele se va identifica prin mail
            $mail_diriginte = Yii::$app->session['user']->username;

            $sql = 'SELECT * FROM diriginti WHERE email="' . $mail_diriginte . '"';
            $record = Diriginti::findBySql($sql, [])->all();

            $dataProvider = Infodiriginti::selectInfodiriginte($mail_diriginte);

            return $this->render('contdiriginte', [
                // 'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
                'email_diriginte' => $mail_diriginte,
                'id_diriginte' => $record[0]['id'],
                'nume_diriginte' => $record[0]['nume'],
                'prenume_diriginte' => $record[0]['prenume']
            ]);
        } else {

            Yii::$app->session->setFlash('error', 'Pentru a continua trebuie sa va logati !!!');
            return $this->redirect([
                'site/index'
            ]);
        }

    }
}

views/infodiriginti/_form.php
<?php

use kartik\select2\Select2;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Infodiriginti */
/* @var $form yii\widgets\ActiveForm */
$lista_judete = \Yii::$app->params['judete'];

?>

<div class="infodiriginti-form">

    <?php $form = ActiveForm::begin(); ?>

    <?php //= $form->field($model, 'sex')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'sex')->widget(Select2::classname(), [
        'data' => ['M' => 'M', 'F' => 'F'],
        'language' => 'ro',
        'options' => ['placeholder' => 'Selecteaza sexul ...'],
        //'disabled' => $model->isNewRecord ? false : true,
        'pluginOptions' => [
            'allowClear' => true,
            'width' => '400px'
        ],
    ])->label('Selecteaza sexul'); ?>

    <?= $form->field($model, 'studii')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'telefon')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'localitate')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'strada')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'numar')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'bloc')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'scara')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'apartament')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>

    <?php //= $form->field($model, 'judet')->textInput(['maxlength' => true,'style' => 'width:400px']) ?>

    <?= $form->field($model, 'judet')->widget(Select2::classname(), [
        'data' => $lista_judete,
        'language' => 'ro',
        'options' => ['placeholder' => 'Selecteaza judetul ...'],
        //'disabled' => $model->isNewRecord ? false : true,
        'pluginOptions' => [
            'allowClear' => true,
            'width' => '400px'
        ],
    ])->label('Selecteaza judetul'); ?>

    <?= $form->field($model, 'buletin_seria')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'buletin_nr')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'grad_didactic')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'vechime')->textInput(['style' => 'width:400px']) ?>

    <div class="form-group">
        <?= Html::submitButton('Salveaza', ['class' => 'btn btn-success']) ?>
        <?= 
        $este_dirigintele_conectat = isset(Yii::$app->session['user']->role) ?
                                        Yii::$app->session['user']->role == 'diriginte' :
                                        false;
        ?>
        <?= Html::a('Renunta', [$este_dirigintele_conectat ? 'infodiriginti/cont-diriginte' : 'site/index'], ['class' => 'btn btn-danger']) ?>

    </div>

    <?php ActiveForm::end(); ?>

</div>

views/infodiriginti/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\InfodirigintiSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="infodiriginti-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'fk_diriginte') ?>

    <?= $form->field($model, 'sex') ?>

    <?= $form->field($model, 'studii') ?>

    <?= $form->field($model, 'telefon') ?>

    <?php // echo $form->field($model, 'localitate') ?>

    <?php // echo $form->field($model, 'strada') ?>

    <?php // echo $form->field($model, 'numar') ?>

    <?php // echo $form->field($model, 'bloc') ?>

    <?php // echo $form->field($model, 'scara') ?>

    <?php // echo $form->field($model, 'apartament') ?>

    <?php // echo $form->field($model, 'judet') ?>

    <?php // echo $form->field($model, 'buletin_seria') ?>

    <?php // echo $form->field($model, 'buletin_nr') ?>

    <?php // echo $form->field($model, 'grad_didactic') ?>

    <?php // echo $form->field($model, 'vechime') ?>

    <?php // echo $form->field($model, 'data_actualizarii') ?>

    <?php // echo $form->field($model, 'data_inregistrarii') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/infodiriginti/contdiriginte.php
<?php

use yii\grid\GridView;
use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $searchModel app\models\ProfesoriSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
$nume = $prenume_diriginte . ' ' . $nume_diriginte;
$this->title = 'Cont diriginte : ';
$this->params['breadcrumbs'][] = $this->title . ' ' . $nume;

?>
<div class="site-about">

    <?php
    if (Yii::$app->session->hasFlash('success')) {
        echo '<div class="alert alert-success" role="alert">';
        echo Yii::$app->session->getFlash('success');
        echo '</div>';
    }
    if (Yii::$app->session->hasFlash('error')) {
        echo '<div class="alert alert-danger" role="alert">';
        echo Yii::$app->session->getFlash('error');
        echo '</div>';
    }
    ?>
    <br>

    <div class="infodiriginti-index">

        <h4><?= Html::encode($this->title . ' ' . $nume) ?></h4>

        <br>

        <p>
            <?= Html::a('Revenire', ['site/index'], ['class' => 'btn btn-success']) ?>

        </p>


        <br><br>



        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

                'diriginti.email',
                'telefon',
                'studii',
                'buletin_seria',
                'buletin_nr',
                'localitate',
                'strada',
                'numar',
                'bloc',
                'scara',
                'apartament',
                'judet',
                'grad_didactic',
                'vechime',

                ['class' => 'yii\grid\ActionColumn',
                    'template' => '{update}',
                ]
            ],

        ]); ?>
        <br><br>

        <?= Html::a('Modifica adresa mail', ['diriginti/schimba-adresa-mail-form'], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Modifica parola', ['diriginti/schimba-parola-form'], ['class' => 'btn btn-success']) ?>


    </div>

views/infodiriginti/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Infodiriginti */

$this->title = 'Adauga diriginte';
$this->params['breadcrumbs'][] = ['label' => 'Infodiriginti', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="infodiriginti-create">

    <h4><?= Html::encode($this->title) ?></h4>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/infodiriginti/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\InfodirigintiSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Infodirigintis';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="infodiriginti-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Infodiriginti', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'fk_diriginte',
            'sex',
            'studii',
            'telefon',
            //'localitate',
            //'strada',
            //'numar',
            //'bloc',
            //'scara',
            //'apartament',
            //'judet',
            //'buletin_seria',
            //'buletin_nr',
            //'grad_didactic',
            //'vechime',
            //'data_actualizarii',
            //'data_inregistrarii',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

views/infodiriginti/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Infodiriginti */

$this->title = 'Editeaza informatii despre diriginte ';
$this->params['breadcrumbs'][] = ['label' => 'Infodiriginti', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Editeaza';
?>
<div class="infodiriginti-update">

    <h4><?= Html::encode($this->title) ?></h4>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/infodiriginti/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Infodiriginti */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Infodirigintis', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="infodiriginti-view">

    <h4><?= Html::encode($this->title) ?></h4>

    <p>
        <?= Html::a('Editeaza', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Sterge', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
        <?=
            $este_dirigintele_conectat = isset(Yii::$app->session['user']->role) ?
                                            Yii::$app->session['user']->role == 'diriginte' :
                                            false;
        ?>
        <?= Html::a('Revenire', [$este_dirigintele_conectat ? 'infodiriginti/cont-diriginte' : 'site/index'], ['class' => 'btn btn-primary']) ?>

    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'fk_diriginte',
            'sex',
            'studii',
            'telefon',
            'localitate',
            'strada',
            'numar',
            'bloc',
            'scara',
            'apartament',
            'judet',
            'buletin_seria',
            'buletin_nr',
            'grad_didactic',
            'vechime',
            'data_actualizarii',
            'data_inregistrarii',
        ],
    ]) ?>

</div>