controllers/ProfesoriController.php
<?php
namespace app\controllers;

use app\controllers\autoGenerated\ProfesoriControllerGenerated;
use app\models\ProfesoriSearch;
use app\models\Admin;
use app\models\Constante;
use app\models\Infoprofesori;
use app\models\Listaclase;
use app\models\Listamaterii;
use app\models\Mediigenerale;
use app\models\Mediisemestriale;
use app\models\Profesori;
use app\models\custom\Utils;
use Yii;
use yii\db\Query;
use app\models\User;

/**
 *
 * @author dan.nicoara
 *
 */
class ProfesoriController extends ProfesoriControllerGenerated
{

    /**
     * Deletes an existing Profesori model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     *
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $este_administratorul_conectat = isset(Yii::$app->session['user']->role) ?
                                    Yii::$app->session['user']->role == 'admin' :
                                    false;
        $este_directorul_conectat = isset(Yii::$app->session['user']->role) ?
            Yii::$app->session['user']->role == 'director' :
            false;

        if (!$este_administratorul_conectat && !$este_directorul_conectat) {
            Yii::$app->session->setFlash('error', 'Nu aveti drepturi pentru a face aceasta operatie !!!');
            return $this->redirect([
                'site/index'
            ]);
        }
        $nume_profesor = Profesori::getNumeProfesor($id);
        $prenume_profesor = Profesori::getPrenumeProfesor($id);


        $this->findModel($id)->delete();
        
        // sterg si inregistrarea corespunzatoare din tabla infoprofesori
        $query = new Query();
        $query->createCommand()
            ->delete('infoprofesori', [
            'fk_profesor' => $id
        ])
            ->execute();

        Yii::$app->session->setFlash('success', 'Profesorul     ' . $nume_profesor . '  ' . $prenume_profesor . '   a fost sters din lista profesorilor scolii');

        return $this->redirect([
            'index'
        ]);
    }

    public function actionSchimbaAdresaMailForm()
    {
        $este_profesorul_conectat = isset(Yii::$app->session['user']->role) ?
                                        Yii::$app->session['user']->role == 'profesor' :
                                        false;

        if ($este_profesorul_conectat) {
            $id_profesor = Yii::$app->session['user']->id;
            return $this->render('changemail', [
                'model' => $this->findModel($id_profesor)
            ]);
        }
        else {
            Yii::$app->session->setFlash('error', 'Pentru a continua trebuie sa va logati !!!');
            return $this->redirect([
                'site/index'
            ]);
        }

    }

    public function actionSchimbaAdresaMail()
    {
        if (!isset($_GET['Profesori']['noul_email']) || empty($_GET['Profesori']['noul_email'])) {
            Yii::$app->session->setFlash('error', 'Nu ati introdus adresa de e-mail !!!');
            return $this->redirect([
                'site/index'
            ]);
        }
        $noul_mail = $_GET['Profesori']['noul_email'];
        $id_profesor = Yii::$app->session['user']->id;
        
        $command = \Yii::$app->db->createCommand('UPDATE profesori SET email="' . $noul_mail . '"  WHERE id=' . $id_profesor);
        $command->execute();
        Yii::$app->session->setFlash('success', 'Adresa de e-mail a fost schimbata . Noua adresa este : ' . $noul_mail);

        // Actualizare adresa de e-mail in sesiune.
        Yii::$app->session['user']->username = $noul_mail;

        return $this->redirect([
            'infoprofesori/cont-profesor',
            'model' => $this->findModel($id_profesor),
        ]);
    }

    /**
     * Schimba parola.
     *
     * @param int $id_profesor
     *            - Id-ul profesorului.
     */
    public function actionSchimbaParolaForm()
    {
        $este_profesorul_conectat = isset(Yii::$app->session['user']->role) ?
                                        Yii::$app->session['user']->role == 'profesor' :
                                        false;

        if ($este_profesorul_conectat) {
            return $this->render('changepassword', [
                'model' => $this->findModel(Yii::$app->session['user']->id)
            ]);
        } else {
            Yii::$app->session->setFlash('error', 'Pentru a continua trebuie sa va logati !!!');
            return $this->redirect([
                'site/index'
            ]);
        }

    }

    /**
     * Schimba parola.
     */
    public function actionSchimbaParola()
    {
        $mesaj = '';
        $vechea_parola = $_GET['Profesori']['vechea_parola'];
        $vechea_parola_criptata = md5($vechea_parola);
        $noua_parola = $_GET['Profesori']['parola'];
        $confirmare_parola = $_GET['Profesori']['confirm_parola'];
        $id_profesor = Yii::$app->session['user']->id;

        $record = Profesori::find()
            ->where(['id' => $id_profesor])
            ->one();

        if ($record == null || $vechea_parola_criptata != $record['parola']) {
            Yii::$app->session->setFlash('error', 'Vechea parola nu este corecta .Reluati procedura !');
            return $this->render('changepassword', [
                'model' => $this->findModel($id_profesor),
            ]);

        }

        if (!empty($noua_parola) && !empty($confirmare_parola) && $noua_parola == $confirmare_parola) {
            //$id_profesor = $_GET['Profesori']['id_profesor'];
            $parola_criptata = md5($noua_parola);
            
            $nume = $_SERVER['SERVER_NAME'];
            $url = $_SERVER['PHP_SELF'];
            $path = pathinfo($nume . $url);
            
            $linksite = $path['dirname'] . "/profesori/login";
            
            $command = \Yii::$app->db->createCommand('UPDATE profesori SET parola="' . $parola_criptata . '"  WHERE id=' . $id_profesor);
            $command->execute();
            
            $model = $this->findModel($id_profesor);
            
            $profesor = new Profesori();
            
            $profesor->sendMailNewParola($model->email, $model->nume, $model->prenume, $linksite, $noua_parola);

            Yii::$app->session->setFlash('success', 'Parola a fost schimbata. Noua parola este  :  ' . $noua_parola);

            return $this->redirect([
                'infoprofesori/cont-profesor',
                'model' => $this->findModel($id_profesor),
            ]);
        } else {
            Yii::$app->session->setFlash('error', 'Nu ati introdus sau nu ati confirmat parola .Reluati procedura !');
            return $this->render('changepassword', [
                'model' => $this->findModel($id_profesor),
            ]);
        }
    }

    /**
     *
     * @return string
     */
    public function actionTrimiteParolaNoua()
    {
        if (isset($_GET['Profesori']['email'])) {
            $email_profesor = $_GET['Profesori']['email'];
            $model = new Profesori();
            
            // se verifica daca email-ul transmis este in tabelul diriginti
            $nume_tabla = ucfirst(Profesori::tableName()); // Prima litera a tablei o transform in litera mare
            $utilizator = Admin::ValidareEmail($email_profesor, $nume_tabla);
            
            if ($utilizator == Null) {
                Yii::$app->session->setFlash('error', "E-mailul introdus nu se afla in baza de date  !");
                $model = new Profesori();
                
                return $this->render('newpassword', [
                    'profesori/newpassword',
                    'model' => $model,
                ]);
            }
            $const = new Constante();
            $parola = $const->generatePassword(); // generez noua parola
                                                  
            // $parola = $model->generatePassword(); // generez noua parola
            $parola_criptata = md5($parola); // criptez parola
            
            $nume = $_SERVER['SERVER_NAME'];
            $url = $_SERVER['PHP_SELF'];
            $path = pathinfo($nume . $url);
            $linksite = $path['dirname'] . "/profesori/login";
            
            $id_profesor = Profesori::cautaProfesorDupaEmail($email_profesor);
            
            // modific parola in bazade date
            $command = \Yii::$app->db->createCommand('UPDATE profesori SET parola="' . $parola_criptata . '"  WHERE id=' . $id_profesor);
            $command->execute();
            
            $model->sendMailProfesor($email_profesor, $linksite, $parola);
            Yii::$app->session->setFlash('success', "Parola a fost schimbata.Verificati-va e-mailul");

            return $this->redirect([
                'site/index',
            ]);
        } else {
            $model = new Profesori();
            Yii::$app->session->setFlash('success', "Va rugam sa introduceti adresa de email :");

            return $this->render('newpassword', [
                'model' => $model,
            ]);
        }
    }

    public function actionSelectezMateriaProfesorului()
    {
        $id_profesor = Yii::$app->session['user']->id;
        $anul_scolar = \Yii::$app->params['anul_scolar'];
        $id_clasa = Yii::$app->session['id_clasa'];
        
        $materii_predate = Listamaterii::getMateriiProfesorClasa($id_profesor, $anul_scolar, $id_clasa);
        $nume_profesor = Yii::$app->session['user']->nume;
        $prenume_profesor = Yii::$app->session['user']->prenume;
        
        $modelmaterii = new Listamaterii();
        $modelmedii = new Mediisemestriale();
        $clase = new Listaclase();
        
        $datele = ListaClase::getClaseProfesor($id_profesor, $anul_scolar);
        
        return $this->render('statisticisitscolara', [
            'id_profesor' => $id_profesor,
            'nume_profesor' => $nume_profesor,
            'prenume_profesor' => $prenume_profesor,

views/profesori/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ProfesoriSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="profesori-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'nume') ?>

    <?= $form->field($model, 'prenume') ?>

    <?= $form->field($model, 'email') ?>


    <?php // echo $form->field($model, 'parola') ?>

    <?php // echo $form->field($model, 'data_inregistrarii') ?>

    <?php // echo $form->field($model, 'data_actualizarii') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/profesori/actualizeaza_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Profesori */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="profesori-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nume')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'prenume')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>


    <?php
    $este_directorul_conectat = isset(Yii::$app->session['user']->role) ?
        Yii::$app->session['user']->role == 'director' :
        false;
    ?>
    <div class="form-group">
        <?= Html::submitButton('Actualizeaza profesor', ['class' => 'btn btn-success']) ?>
        <?= Html::a('Renunta', [$este_directorul_conectat ? 'profesori/index' : 'admin/administrator-adauga'], ['class' => 'btn btn-danger']) ?>

    </div>

    <?php ActiveForm::end(); ?>

</div>

views/profesori/afisaremediisemclasamaterie.php
<?php

use app\models\Elevi;
use kartik\export\ExportMenu;
use yii\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel app\models\CatalognoteSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
if ($semestrul == 'I' || $semestrul == 'II')
    $this->title = 'Mediile semestriale ale  elevilor clasei : ' . $nume_clasa;

if ($semestrul == 'MG')
    $this->title = 'Mediile anuale ale  elevilor clasei : ' . $nume_clasa;

$this->params['breadcrumbs'][] = $this->title;


?>
<div class="clasa-index">

    <h4><?= Html::encode($this->title) ?></h4>

    <br>

    <p>
        <?= Html::a('Revenire la pagina principala', ['site/index'], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Revenire la selectii', ['profesori/selectez-materia-profesorului'], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Lista elevilor clasei', ['elevi/afisare-clasa'], ['class' => 'btn btn-success']) ?>

    </p>
    <br>
    <?php if (isset($mesaj))
        echo '<span style="color:red "><h5>' . Html::encode($mesaj) . '</h5></span>';
    ?>
    <?php if (Yii::$app->request->get('mesaj'))
        echo '<span style="color:red "><h5>' . Html::encode(Yii::$app->request->get('mesaj')) . '</h5></span>';
    ?>
    <br><br>
    <?php
    $gridColumns = [
        ['class' => 'kartik\grid\SerialColumn'],

        'nr_matricol',
        'nume',
        'prenume',
        'materia',
        'nota',
        'sem',

        ['class' => 'kartik\grid\ActionColumn', 'urlCreator' => function () {
            return '#';
        }],
    ];
    ?>
    <?= ExportMenu::widget([
        'dataProvider' => $dataProvider,
        'columns' => $gridColumns,
        'fontAwesome' => true,
        'dropdownOptions' => [
            'label' => 'Exporta',
            'class' => 'btn btn-default',
        ],
    ]);
    // Renders a export dropdown menu
    ?>
    <br><br>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'label' => 'Numar matricol',
                'content' => function ($data) {
                    $nr_matricol = $data['nr_matricol'];
                    return $nr_matricol;
                },
                'format' => 'text'
            ],
            'nume',
            'prenume',
            [
                'label' => 'Materia',
                'content' => function ($data) {
                    $materia = $data['materia'];
                    return $materia;
                },
                'format' => 'text'
            ],

            [
                'label' => 'Media',
                'content' => function ($data) {
                    $media = $data['media'];
                    return $media;
                },
                'format' => 'text'
            ],
            [
                'label' => 'Semestrul',
                'attribute' => 'sem',
                'visible' => ($semestrul == 'I' || $semestrul == 'II'),
            ],
            //'sem'

//            ['class' => 'yii\grid\ActionColumn',
//                'template' => '{view} {update} {delete} ',
//            ]

        ],

    ]); ?>


</div>

views/profesori/changemail.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<?php
$this->title = 'Introduceti noua adresa de e-mail';
$this->params['breadcrumbs'][] = $this->title;


?>
<div class="site-about">
    <div class="changeMail-form">
        <?php $form = ActiveForm::begin([
            'action' => ['profesori/schimba-adresa-mail'],
            'method' => 'get',
        ]);
        ?>
        <?= $form->field($model, 'email')->textInput(['readonly' => true])->label('E-mailul curent') ?>
        <?= $form->field($model, 'noul_email')->input('email')->label('Introduceti noul e-mail') ?>


        <?= Html::activeHiddenInput($model, 'id_profesor', ['value' => $model->id]) ?>

        <div class="form-group">
            <?= Html::submitButton('Schimba adresa e-mail', ['class' => 'btn btn-success']) ?>
        </div>

        <?php ActiveForm::end(); ?>

        <?= Html::a('Revenire in cont profesor', ['infoprofesori/cont-profesor'], ['class' => 'btn btn-success']) ?>

    </div>

</div>

views/profesori/changepassword.php
<?php
use kartik\password\PasswordInput;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<?php
$this->title = 'Introduceti noua parola';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">

    <?php
    if (Yii::$app->session->hasFlash('success')) {
        echo '<div class="alert alert-success" role="alert">';
        echo Yii::$app->session->getFlash('success');
        echo '</div>';
    }
    if (Yii::$app->session->hasFlash('error')) {
        echo '<div class="alert alert-danger" role="alert">';
        echo Yii::$app->session->getFlash('error');
        echo '</div>';
    }
    ?>
    <br>


    <div class="changePassword-form">

        <?php $form = ActiveForm::begin([
            'action' => ['profesori/schimba-parola'],
            'method' => 'get',

        ]);

        ?>
        <div class="row">
            <div class="col-md-12">
        <?php $model->parola = ''; ?>

        <?= $form->field($model, 'vechea_parola', ['labelOptions' => ['class' => 'col-sm-3 col-md-3 col-lg-3']])->widget(PasswordInput::classname(), [])->label('Introduceti vechea parola') ?>

        <?= $form->field($model, 'parola', ['labelOptions' => ['class' => 'col-sm-3 col-md-3 col-lg-3']])->widget(PasswordInput::classname(), [])->label('Introduceti noua parola') ?>

        <?= $form->field($model, 'confirm_parola', ['labelOptions' => ['class' => 'col-sm-3 col-md-3 col-lg-3']])->widget(PasswordInput::classname(), [])->label('Confirmati parola       ') ?>
            </div>
        </div>

        <?= Html::activeHiddenInput($model, 'id_profesor', ['value' => $model->id]) ?>

        <div class="form-group">
            <?= Html::submitButton('Modifica parola', ['class' => 'btn btn-primary']) ?>
        </div>

        <?php ActiveForm::end(); ?>

        <?= Html::a('Revenire in cont profesor', ['infoprofesori/cont-profesor'], ['class' => 'btn btn-success']) ?>

    </div>

</div>

views/profesori/create.php
<?php



/* @var $this yii\web\View */
/* @var $model app\models\Profesori */

$this->title = 'Adauga profesor';
$this->params['breadcrumbs'][] = ['label' => 'Profesori', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="profesori-create">


    <?= $this->render('creaza_form', [
        'model' => $model,

    ]) ?>

</div>

views/profesori/creaza_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Profesori */
/* @var $form yii\widgets\ActiveForm */
?>
<?php
if (Yii::$app->session->hasFlash('success')) {
    echo '<div class="alert alert-success" role="alert">';
    echo Yii::$app->session->getFlash('success');
    echo '</div>';
}
if (Yii::$app->session->hasFlash('error')) {
    echo '<div class="alert alert-danger" role="alert">';
    echo Yii::$app->session->getFlash('error');
    echo '</div>';
}
?>
<br>
<div class="profesori-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nume')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'prenume')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>




    <div class="form-group">
        <?= Html::submitButton('Adauga profesor', ['class' => 'btn btn-success']) ?>
        <?= Html::a('Renunta', ['admin/administrator-adauga'], ['class' => 'btn btn-danger']) ?>

    </div>

    <?php ActiveForm::end(); ?>

</div>

views/profesori/index.php
<?php

use exocet\BootstrapMD\widgets\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ProfesoriSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Lista profesorilor scolii';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="profesori-index">

    <h4><?= Html::encode($this->title) ?></h4>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?php
    if (Yii::$app->session->hasFlash('success')) {
        echo '<div class="alert alert-success" role="alert">';
        echo Yii::$app->session->getFlash('success');
        echo '</div>';
    }
    if (Yii::$app->session->hasFlash('error')) {
        echo '<div class="alert alert-danger" role="alert">';
        echo Yii::$app->session->getFlash('error');
        echo '</div>';
    }
    ?>
    <br>

    <p>
        <?= Html::a('Adauga profesor', ['create'], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Revenire la pagina principala', ['site/index'], ['class' => 'btn btn-primary']) ?>

    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'nume',
            'prenume',
            'email:email',
            ['class' => 'yii\grid\ActionColumn',
                'template' => /*'{create} {view}*/
                    '{info} {catedra} {update} {delete}',
                'buttons' => [
                    'info' => function ($url, $model, $id) {
                        $url = Yii::$app->urlManager->createUrl(['infoprofesori/view', 'id' => $id]);
                        return Html::a('<span class="glyphicon glyphicon-info-sign"></span>', $url, ['title' => Yii::t('app', 'Informatii despre profesor')]);
                    },
                    'catedra' => function ($url, $model, $id) {
                        $url = Yii::$app->urlManager->createUrl(['directori/catedra-profesor', 'id_prof' => $id]);
                        return Html::a('<span class="glyphicon glyphicon-calendar"></span>', $url, ['title' => Yii::t('app', 'Catedra profesorului')]);
                    },
                ]
            ],
        ],
    ]); ?>
</div>

views/profesori/login.php
<?php
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */
if (isset($_GET['user']))
    $utilizator = $_GET['user'];
else
    $utilizator = '';

$this->title = 'Logare' . ' ' . $utilizator;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h4><?= Html::encode($this->title) ?></h4>

    <p>Va rugam sa completati urmatoarele campuri pentru a va loga :</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'parola')->passwordInput() ?>

    <!--    --><?php //= $form->field($model, 'rememberMe', [
    //        'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
    //    ])->checkbox() ?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>

    <br>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::a('Ati uitat parola ?', ['profesori/trimite-parola-noua'], ['class' => 'btn btn-success']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>


</div>

views/profesori/newpassword.php
<?php
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

$this->title = 'Parola pierduta';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="diriginti-newpassword">
    <h4><?= Html::encode($this->title) ?></h4>

    <?php
    if (Yii::$app->session->hasFlash('success')) {
        echo '<div class="alert alert-success" role="alert">';
        echo Yii::$app->session->getFlash('success');
        echo '</div>';
    }
    if (Yii::$app->session->hasFlash('error')) {
        echo '<div class="alert alert-danger" role="alert">';
        echo Yii::$app->session->getFlash('error');
        echo '</div>';
    }
    ?>
    <br>


    <div class="newpassword-form">

        <?php $form = ActiveForm::begin([
            'action' => ['profesori/trimite-parola-noua'],
            'method' => 'get',
            'options' => ['class' => 'form-horizontal'],
            'fieldConfig' => [
                'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
                'labelOptions' => ['class' => 'col-lg-1 control-label'],
            ],
        ]);

        ?>
        <?= $form->field($model, 'email')->textInput(['readonly' => false])->label('E-mailul') ?>


        <div class="form-group">
            <?= Html::submitButton('Trimite', ['class' => 'btn btn-primary']) ?>

        </div>
        <div class="form-group">
            <?= Html::a('Revenire in pagina de logare', ['profesori/login'], ['class' => 'btn btn-success']) ?>


        </div>

        <?php ActiveForm::end(); ?>


    </div>


</div>

views/profesori/statisticisitscolara.php
<?php
use kartik\select2\Select2;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<?php
$this->title = 'Afisare mediilor elevilor clasei la obiectul selectat';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="site-about">
    <h4><?= Html::encode($this->title) ?></h4>

    <div class="classProfesori-form">


        <?php $form = ActiveForm::begin([
            'action' => ['profesori/profesor-afisez-medii-clasa-elevi'],
            'method' => 'get',
        ]);
        ?>
        <?php

        echo $form->field($modelmaterii, 'id')->widget(Select2::classname(), [
            //'data' => ArrayHelper::map(CartiCustom::CartiDisponibile(), 'id_carte', 'titlu_carte'),
            'name' => 'profesorul',
            'data' => $materii_predate,
            'language' => 'ro',
            'size' => 'md',
            'options' => ['placeholder' => 'Selecteaza materia ...'],
            'pluginOptions' => [
                'allowClear' => true,
                'width' => '300px'
            ],
        ])->label('Selecteaza materia');

        ?>

        <?= $form->field($modelmedii, 'sem')->widget(Select2::classname(), [
            'data' => ['I' => 'Medii semestrul I', 'II' => 'Medii semestrul II', 'MG' => 'Medii anuale'],
            'language' => 'ro',
            'options' => ['placeholder' => 'Selecteaza optiunea ...'],
            'pluginOptions' => [
                'allowClear' => true,
                'width' => '300px',
            ],
        ])->label('Selecteaza optiunea de afisare'); ?>


        <div class="form-group">
            <?= Html::submitButton('Afiseaza', ['class' => 'btn btn-success']) ?>
        </div>

        <?php ActiveForm::end(); ?>


    </div>

</div>

views/profesori/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Profesori */

$this->title = 'Editeaza lista profesorilor';
$this->params['breadcrumbs'][] = ['label' => 'Profesori', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="profesori-update">

    <h4><?= Html::encode($this->title) ?></h4>

    <?= $this->render('actualizeaza_form', [
        'model' => $model,
    ]) ?>

</div>