models/Infodirectori.php
<?php
namespace app\models;

use app\models\autoGenerated\InfodirectoriGenerated;
use Yii;
use yii\data\ActiveDataProvider;

class Infodirectori extends InfodirectoriGenerated
{
    /**
     * Selecteaza informatii despre director.
     *
     * @param
     *            $mail_director
     * @return ActiveDataProvider
     */
    public static function selectInfodirector($mail_director)
    {
        $query = Infodirectori::find()->joinWith('directori');

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 2
            ]
        ]);

        $query->andFilterWhere([
            'email' => $mail_director
            // 'parola'=> $this->parola,
        ]);
        return $dataProvider;
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            // indiferent daca este inserare sau actualizare se introduce data curenta in campul data_actualizarii
            $this->data_actualizarii = date('Y-m-d H:i:s');
            return true;
        } else {
            return false;
        }
    }

    /***
     * Returneaza lista de directori.
     * 
     * @return unknown
     */
    public function getDirectori()
    {
        return $this->hasOne(Directori::className(), [
            'id' => 'fk_director'
        ]);
    }
}

controllers/InfodirectoriController.php
<?php
namespace app\controllers;

use app\controllers\autoGenerated\InfodirectoriControllerGenerated;
use app\models\Directori;
use app\models\Infodirectori;
use Yii;

/**
 * InfodirectoriController implements the CRUD actions for Infodirectori model.
 */
class InfodirectoriController extends InfodirectoriControllerGenerated
{

    /**
     * Lists all Infodirectori models.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $este_administratorul_conectat = isset(Yii::$app->session['user']->role) ?
            Yii::$app->session['user']->role == 'admin' :
            false;

        $este_directorul_conectat = isset(Yii::$app->session['user']->role) ?
            Yii::$app->session['user']->role == 'director' :
            false;

        $este_secretarul_conectat = isset(Yii::$app->session['user']->role) ?
            Yii::$app->session['user']->role == 'secretar' :
            false;

        if (!$este_administratorul_conectat &&
            !$este_directorul_conectat &&
            !$este_secretarul_conectat
        ) {
            Yii::$app->session->setFlash('error', 'Nu aveti drepturi pentru a accesa aceasta sectiune !!!');
            return $this->redirect([
                'site/index'
            ]);
        }
        $searchModel = new InfodirectoriSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * Displays a single Infodirectori model.
     *
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $este_administratorul_conectat = isset(Yii::$app->session['user']->role) ?
            Yii::$app->session['user']->role == 'admin' :
            false;

        $este_directorul_conectat = isset(Yii::$app->session['user']->role) ?
            Yii::$app->session['user']->role == 'director' :
            false;

        $este_secretarul_conectat = isset(Yii::$app->session['user']->role) ?
            Yii::$app->session['user']->role == 'secretar' :
            false;

        if (!$este_administratorul_conectat &&
            !$este_directorul_conectat &&
            !$este_secretarul_conectat
        ) {
            Yii::$app->session->setFlash('error', 'Nu aveti drepturi pentru a accesa aceasta sectiune !!!');
            return $this->redirect([
                'site/index'
            ]);
        }
        return $this->render('view', [
            'model' => $this->findModel($id)
        ]);
    }

    /**
     * Creates a new Infodirectori model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @return mixed
     */
    public function actionCreate()
    {
        $este_administratorul_conectat = isset(Yii::$app->session['user']->role) ?
                                    Yii::$app->session['user']->role == 'admin' :
                                    false;

        if ((!$este_administratorul_conectat)
        ) {
            Yii::$app->session->setFlash('error', 'Nu aveti drepturi pentru a accesa aceasta sectiune !!!');
            return $this->redirect([
                'site/index'
            ]);
        }
        $model = new Infodirectori();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect([
                'view',
                'id' => $model->id
            ]);
        }

        return $this->render('create', [
            'model' => $model
        ]);
    }

    /**
     * Updates an existing Infodirectori model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $este_administratorul_conectat = isset(Yii::$app->session['user']->role) ?
            Yii::$app->session['user']->role == 'admin' :
            false;

        $este_directorul_conectat = isset(Yii::$app->session['user']->role) ?
            Yii::$app->session['user']->role == 'director' :
            false;

        if (!$este_administratorul_conectat &&
            !$este_directorul_conectat
        ) {
            Yii::$app->session->setFlash('error', 'Nu aveti drepturi pentru a accesa aceasta sectiune !!!');
            return $this->redirect([
                'site/index'
            ]);
        }
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect([
                'view',
                'id' => $model->id
            ]);
        }

        return $this->render('update', [
            'model' => $model
        ]);
    }

    /**
     * Deletes an existing Infodirectori model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     *
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $este_administratorul_conectat = isset(Yii::$app->session['user']->role) ?
            Yii::$app->session['user']->role == 'admin' :
            false;

        $este_directorul_conectat = isset(Yii::$app->session['user']->role) ?
            Yii::$app->session['user']->role == 'director' :
            false;

        if (!$este_administratorul_conectat &&
            !$este_directorul_conectat
        ) {
            Yii::$app->session->setFlash('error', 'Nu aveti drepturi pentru a accesa aceasta sectiune !!!');
            return $this->redirect([
                'site/index'
            ]);
        }
        $this->findModel($id)->delete();

        return $this->redirect([
            'index'
        ]);
    }
    /**
     * Afiseaza contul directorului.
     */
    public function actionContDirector()
    {
        $este_directorul_conectat = isset(Yii::$app->session['user']->role) ?
            Yii::$app->session['user']->role == 'director' :
            false;
        if ($este_directorul_conectat) {
            // cititorul se va identifica prin mail
            $mail_director = Yii::$app->session['user']->username;

            $sql = 'SELECT * FROM directori WHERE email="' . $mail_director . '"';
            $record = Directori::findBySql($sql, [])->all();

            $dataProvider = Infodirectori::selectInfodirector($mail_director);

            return $this->render('contdirector', [
                // 'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
                'email_director' => $mail_director,
                'id_director' => $record[0]['id'],
                'nume_director' => $record[0]['nume'],
                'prenume_director' => $record[0]['prenume']
            ]);
        } else {
            Yii::$app->session->setFlash('error', 'Pentru a continua trebuie sa va logati !!!');
            return $this->redirect([
                'site/index'
            ]);
        }

    }
}

views/infodirectori/_form.php
<?php

use kartik\select2\Select2;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Infodirectori */
/* @var $form yii\widgets\ActiveForm */
$lista_judete = \Yii::$app->params['judete'];

?>

<div class="infodirectori-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'sex')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'studii')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'telefon')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'localitate')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'strada')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'numar')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'bloc')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'scara')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'apartament')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>

    <?php //= $form->field($model, 'judet')->textInput(['maxlength' => true,'style' => 'width:400px']) ?>

    <?= $form->field($model, 'judet')->widget(Select2::classname(), [
        'data' => $lista_judete,
        'language' => 'ro',
        'options' => ['placeholder' => 'Selecteaza judetul ...'],
        //'disabled' => $model->isNewRecord ? false : true,
        'pluginOptions' => [
            'allowClear' => true,
            'width' => '400px'
        ],
    ])->label('Selecteaza judetul'); ?>

    <?= $form->field($model, 'buletin_seria')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'buletin_nr')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'grad_didactic')->textInput(['maxlength' => true, 'style' => 'width:400px']) ?>

    <?= $form->field($model, 'vechime')->textInput(['style' => 'width:400px']) ?>

    <div class="form-group">
        <?= Html::submitButton('Salveaza', ['class' => 'btn btn-success']) ?>
        <?= Html::a('Renunta', ['infodirectori/cont-director'], ['class' => 'btn btn-danger']) ?>

    </div>

    <?php ActiveForm::end(); ?>

</div>

views/infodirectori/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\InfodirectoriSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="infodirectori-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'fk_director') ?>

    <?= $form->field($model, 'sex') ?>

    <?= $form->field($model, 'studii') ?>

    <?= $form->field($model, 'telefon') ?>

    <?php // echo $form->field($model, 'localitate') ?>

    <?php // echo $form->field($model, 'strada') ?>

    <?php // echo $form->field($model, 'numar') ?>

    <?php // echo $form->field($model, 'bloc') ?>

    <?php // echo $form->field($model, 'scara') ?>

    <?php // echo $form->field($model, 'apartament') ?>

    <?php // echo $form->field($model, 'judet') ?>

    <?php // echo $form->field($model, 'buletin_seria') ?>

    <?php // echo $form->field($model, 'buletin_nr') ?>

    <?php // echo $form->field($model, 'grad_didactic') ?>

    <?php // echo $form->field($model, 'vechime') ?>

    <?php // echo $form->field($model, 'data_actualizarii') ?>

    <?php // echo $form->field($model, 'data_inregistrarii') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/infodirectori/contdirector.php
<?php

use yii\grid\GridView;
use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $searchModel app\models\ProfesoriSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
$nume = $prenume_director . ' ' . $nume_director;
$this->title = 'Cont director : ';
$this->params['breadcrumbs'][] = $this->title . ' ' . $nume;

?>
<div class="site-about">

    <?php
    if (Yii::$app->session->hasFlash('success')) {
        echo '<div class="alert alert-success" role="alert">';
        echo Yii::$app->session->getFlash('success');
        echo '</div>';
    }
    if (Yii::$app->session->hasFlash('error')) {
        echo '<div class="alert alert-danger" role="alert">';
        echo Yii::$app->session->getFlash('error');
        echo '</div>';
    }
    ?>
    <br>

    <div class="infodirectori-index">

        <h4><?= Html::encode($this->title . ' ' . $nume) ?></h4>

        <br>

        <p>
            <?= Html::a('Revenire la pagina principala', ['site/index'], ['class' => 'btn btn-success']) ?>

        </p>


        <br><br>



        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

                'directori.email',
                'telefon',
                'studii',
                'buletin_seria',
                'buletin_nr',
                'localitate',
                'strada',
                'numar',
                'bloc',
                'scara',
                'apartament',
                'judet',
                'grad_didactic',
                'vechime',

                ['class' => 'yii\grid\ActionColumn',
                    'template' => '{update}',
                ]
            ],

        ]); ?>
        <br><br>

        <?= Html::a('Modifica adresa mail', ['directori/schimba-adresa-mail-form'], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Modifica parola', ['directori/schimba-parola-form'], ['class' => 'btn btn-success']) ?>


    </div>

views/infodirectori/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Infodirectori */

$this->title = 'Adauga director';
$this->params['breadcrumbs'][] = ['label' => 'Infodirectori', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="infodirectori-create">

    <h4><?= Html::encode($this->title) ?></h4>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/infodirectori/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\InfodirectoriSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Infodirectoris';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="infodirectori-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Infodirectori', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'fk_director',
            'sex',
            'studii',
            'telefon',
            //'localitate',
            //'strada',
            //'numar',
            //'bloc',
            //'scara',
            //'apartament',
            //'judet',
            //'buletin_seria',
            //'buletin_nr',
            //'grad_didactic',
            //'vechime',
            //'data_actualizarii',
            //'data_inregistrarii',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

views/infodirectori/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Infodirectori */

$this->title = 'Editeaza informatii despre directori ';
$this->params['breadcrumbs'][] = ['label' => 'Infodirectoris', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Editeaza';
?>
<div class="infodirectori-update">

    <h4><?= Html::encode($this->title) ?></h4>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/infodirectori/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Infodirectori */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Infodirectoris', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="infodirectori-view">

    <h4><?= Html::encode($this->title) ?></h4>

    <p>
        <?= Html::a('Editeaza', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Sterge', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
        <?php
        $este_directorul_conectat = isset(Yii::$app->session['user']->role) ?
            Yii::$app->session['user']->role == 'director' :
            false;
        ?>
        <?= Html::a('Revenire', [$este_directorul_conectat ? 'infodirectori/cont-director' : 'site/index'], ['class' => 'btn btn-primary']) ?>

    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            //'fk_director',
            'sex',
            'studii',
            'telefon',
            'localitate',
            'strada',
            'numar',
            'bloc',
            'scara',
            'apartament',
            'judet',
            'buletin_seria',
            'buletin_nr',
            'grad_didactic',
            'vechime',
            'data_actualizarii',
            'data_inregistrarii',
        ],
    ]) ?>

</div>